### ISSUE TITLE
merge is not defined helpers.js

### ISSUE THREAD

**Issue by ymarcon** [mesqueeb/blitzar#90]
I have this error with version 1.0.5:

```
Uncaught (in promise) ReferenceError: merge is not defined
    at getBlitzFieldOverwrites (webpack-internal:///./node_modules/@blitzar/form/dist/components/helpers.js:14)
```

Looks like this import is missing in `form/src/components/helpers.js`:

```
import { merge } from 'merge-anything'
```

**Comment by mesqueeb** [comment]
@ymarcon sorry I broke a bunch of stuff last release. Will get a fix out in few hours

**Comment by mesqueeb** [comment]
@ymarcon should be fixed with latest version. please give it a try : )

**Comment by cess11** [comment]
Had the same problem, works for me after reinstalling @blitzar/form@next with yarn.

**Comment by ymarcon** [comment]
@cess11 @next gets 1.0.3, which works. When getting 1.0.6, it still fails, but differently:

```
 App •  ERROR  •  UI  in ./node_modules/@blitzar/types/src/index.ts

Module not found: Can't resolve imported dependency "./core"

 App •  ERROR  •  UI  in ./node_modules/@blitzar/types/src/index.ts

Module not found: Can't resolve imported dependency "./table"
```

**Comment by mesqueeb** [comment]
@ymarcon is it a public repo?or can you share via email ?

**Comment by mesqueeb** [comment]
@cess11
Do you have any issues on `npm i blitzar@latest`
And import like so:

```
import { BlitzForm } from 'blitzar'
```

**Comment by ymarcon** [comment]
Yes, `yarn add blitzar@latest` works, but I get `@blitzar/form` version 1.0.3, which works.

You can give it a try with the project [obiba/quasar-ui-amber](https://github.com/obiba/quasar-ui-amber)

```
cd ui
yarn
yarn dev
```

**Comment by ymarcon** [comment]
I have cleaned my environment, `yarn add blitzar@latest` gets 1.0.6 as expected, I have also changed the `import` directives as you mentioned, but it does not work.

```
$ yarn dev
yarn run v1.22.5
$ cd dev && yarn dev && cd ..
$ quasar dev

 Dev mode.......... spa
 Pkg quasar........ v2.3.3
 Pkg @quasar/app... v3.2.3
 Pkg webpack....... v5
 Debugging......... enabled

 Configured browser support (>= 89.41% of global marketshare):
 · Chrome for Android >= 95
 · Firefox for Android >= 92
 · Android >= 95
 · Chrome >= 87
 · Edge >= 92
 · Firefox >= 85
 · iOS >= 11.3-11.4
 · Opera >= 77
 · Safari >= 12.1

 App • Chaining "UI" Webpack config
 App •  WAIT  • Compiling of "UI" in progress...
 App •  DONE  • "UI" compiled with errors • 7122ms



 App •  ERROR  •  UI  in ./node_modules/@blitzar/types/src/index.ts

Module not found: Can't resolve imported dependency "./core"

 App •  ERROR  •  UI  in ./node_modules/@blitzar/types/src/index.ts

Module not found: Can't resolve imported dependency "./table"


 App •  COMPILATION FAILED  • Please check the log above for details.
```

**Comment by ymarcon** [comment]
Looks like there is no `build` script in the `types` sub-package.

**Comment by mesqueeb** [comment]
@ymarcon the types package is a pure TS package consumed by the other packages. Should not cause any issues, maybe something related to webpack. 
I have some time later tonight, will check your project locally  : )

**Comment by mesqueeb** [comment]
@ymarcon sorry I'm too tired today, just finished work and it's 01:00 AM 😱

I'll try to look at your repo tomorrow.

**Comment by mesqueeb** [comment]
@ymarcon thank you for the reproduction. I was able to fix the issue on the latest version `1.0.7`!

I have tested on your repo and it worked on my end now.

Let me know if there's anything else! 🎉

**Comment by ymarcon** [comment]
Excellent, that works thanks!
